# Window Customization
window:
  opacity: 0.8
  dimensions:
    columns: 160
    lines: 60
  padding:
    x: 25
    y: 25
  decorations: none
scrolling:
  history: 10000
  multiplier: 3
window.dynamic_title: true

font:
  normal: 

    family: FiraCode

    style: Regular 

  bold:

    family: FiraCode

    style: Bold

  italic:

    family: FiraCode

    style: Italic

  bold_italic:

    family: FiraCode

    style: Bold Italic

  size: 15.0


# Gruvbox Material Dark Medium - alacritty color config
# by sainnhe https://github.com/sainnhe/gruvbox-material
colors:
  # Default colors
  primary:
    background: '0x282828'
    foreground: '0xd4be98'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text:   '0x504945'
    cursor: '0xd4be98'

  # Normal colors
  normal:
    black:   '0x504945'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xf2f2f2'

  # Bright colors
  bright:
    black:   '0x504945'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0x928374'

  indexed_colors:
    - { index: 16, color: '0xdc9656' }
    - { index: 17, color: '0xa16946' }
    - { index: 18, color: '0x282828' }
    - { index: 19, color: '0x383838' }
    - { index: 20, color: '0xb8b8b8' }
    - { index: 21, color: '0xe8e8e8' }

  selection:
    text: '0xffffff'
    background: '0xdc3232'
    white:   '0xffffff'

cursor:
  style: Block
  unfocused_hollow: true
mouse:
      hide_when_typing: true
key_bindings:
  - { key: N, mods: Control, action: SpawnNewInstance }

#||\\ //||
#|| \// || Mackenzie Criswell
#|| //\ || https://makc.co
#||   \\|| https://github.com/makccr

